spring.application.name=usebylu
spring.datasource.url=jdbc:postgresql://localhost:5432/usebylu
spring.datasource.username=postgres
spring.datasource.password=CaPostSQL
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.docker.compose.enabled=false